CREATE TABLE Account (
  AccountID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  LoginCode INT NOT NULL,
  Password VARCHAR(50) NOT NULL,
  Name VARCHAR(50) NOT NULL,
  Team INT NOT NULL
);

CREATE TABLE Bus (
  BusID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  BusNumber INT NOT NULL,
  BatteryLevel INT NOT NULL,
  Status INT NOT NULL,
  PeriodicCleaning DATETIME NOT NULL,
  PeriodicMaintenance DATETIME NOT NULL
);

CREATE TABLE ParkingSpace (
  ParkingSpaceID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  BusID INT NOT NULL,
  Number INT NOT NULL,
  Type INT NOT NULL,
  Occupied BOOLEAN NOT NULL
);

CREATE TABLE Cleaning (
  CleaningID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  BusID INT NOT NULL,
  CleanedBy INT NOT NULL,
  TimeCleaned DATETIME NOT NULL,
  Status INT NOT NULL
);

CREATE TABLE AdHoc (
  AdHocID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  BusID INT NOT NULL,
  Type INT NOT NULL,
  Team INT NOT NULL,
  Description VARCHAR(50) NOT NULL,
  TimeDone DATETIME NOT NULL
);